#!/usr/bin/env python3
import tempfile

import rospy
from arm_kinematics.widowx import WidowX

if __name__ == '__main__':
    rospy.init_node('fk_broadcaster_node')
    rospy.loginfo("Creating fk_broadcaster")

    urdf_xml = rospy.get_param("wx250s/robot_description")

    with tempfile.NamedTemporaryFile("w", delete=False, suffix=".urdf") as f:
        f.write(urdf_xml)
        urdf_path = f.name

    robot = WidowX(urdf_path)

    rospy.spin()
