#!/usr/bin/env python

import time

import rospy
from std_msgs.msg import Bool

from car_final_project.security_bot import SecurityBot


if __name__ == '__main__':
    rospy.init_node('surveillance_bot')
    bot = SecurityBot()
    start_time = time.time()
    # start_time = bot.start_time
    msg = rospy.wait_for_message('/car_status', Bool)
    while not bot.traversal_complete:
        bot.publish_goal()
    print('done')
    time_taken = time.time() - start_time
    bot.submission_file.write("Room visit order: {}\n".format(bot.room_check_order))
    bot.submission_file.write("Time taken: {}\n".format(time_taken))
    bot.submission_file.write("Cathy's life:{}\n".format(bot.life))
    bot.submission_file.write("Efficiency:{}\n".format(bot.life/time_taken))

    is_alive = (bot.life-bot.doctor_time)>0 and (time_taken<bot.doctor_time)
    bot.submission_file.write("Is Cathy alive?:{}".format(is_alive))

    rospy.loginfo("Surveillance successfully completed in {}".format(time_taken))
